### ISSUE TITLE
Set a background task to refresh the materialized view

### ISSUE THREAD

**Issue by ifirmawan** [akvo/wai-sdg-portal#294]
### TODO/Done

- [ ] After the datapoint is created.
- [ ] After the datapoint is updated.
- [ ] After the datapoint is deleted.

**Comment by dedenbangkit** [comment]
test comment
