### ISSUE TITLE
Update waterpoints questionnaires

### ISSUE THREAD

**Issue by ifirmawan** [akvo/wai-sdg-portal#333]
## TODO/DONE

- [x] Fix empty categories on the FE side
- [x] Update waterpoints questionnaires Uganda
- [x] Update waterpoints questionnaires Ethiopia
- [x] Update selected waterpoints questionnaires as optional Uganda
