### ISSUE TITLE
Add project code validation in bulk upload 

### ISSUE THREAD

**Issue by ifirmawan** [akvo/wai-sdg-portal#389]
### TODO/DONE

- [ ] Add validation for the answer list
- [ ] Set datapoint name from the parent project
- [ ] Update unit test for bulk upload
