### ISSUE TITLE
Uganda School questionnaires changes

### ISSUE THREAD

**Issue by ifirmawan** [akvo/wai-sdg-portal#407]
## TODO/DONE

- [ ]  Add "Rainwater Harvesting Tank" to the options for Main Drinking Water Source.  This is also shown in the JMP logic file.
- [ ] Add two questions.  
  - [ ] a)  How many functioning stances are for females? 
  - [ ] b)  How many functioning stances are for boys? These two questions are NOT connected to the JMP logic.
- [ ] Remove the JMP logic for two questions:  
  - [ ] a) are the toilets for girls clean? 
  - [ ] b) are the toilets for boys clean?
- [ ] Change the dependency for "673264019|Is drinking water from the main source currently available at the school at the time of the survey,"  to include "tubewell/borehole"
