### ISSUE TITLE
Update landing pages

### ISSUE THREAD

**Issue by ifirmawan** [akvo/wai-sdg-portal#434]
## TODO/DONE

- [ ] Replace the carousel with tabs containing a Pie chart
- [ ] Create config for each instance
- [ ] Implements Non-JMP Chart
- [ ] Implements JMP Chart

Reference
[https://app.asana.com/0/1204165942038801/1205937576449708/f](https://app.asana.com/0/1204165942038801/1205937576449708/f)
